name: StyleCheck
on:
  pull_request:
  workflow_dispatch: # add manual trigger button

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run Checkstyle
        run: |
          ./gradlew checkstyleMain checkstyleTest --continue

      - uses: reviewdog/action-setup@v1.4.0

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for xmlReport in {.,integration-tests}/build/reports/checkstyle/*.xml; do \
            cat $xmlReport | reviewdog -f=checkstyle -log-level=warning -reporter=github-pr-review; \
          done
